# Generated by Django 4.2.10 on 2025-06-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='院系ID'),
        ),
    ]
