# Generated by Django 4.2.23 on 2025-06-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_consolidated_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classschedule",
            name="class_date",
            field=models.DateField(default="2025-01-01", verbose_name="上课日期"),
        ),
    ]
