# Generated by Django 4.2.20 on 2025-06-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_add_class_date_to_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='scan_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='扫码结束时间'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='scan_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='扫码开始时间'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='class_date',
            field=models.DateField(verbose_name='上课日期'),
        ),
    ]
