# Generated by Django 4.2.10 on 2025-06-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_department_dept_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='major_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='专业ID'),
        ),
    ]
