# Generated by Django 4.2.10 on 2025-06-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_major_major_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingassignment',
            name='assignment_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='教学安排ID'),
        ),
    ]
