# Generated by Django 4.2.20 on 2025-06-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_classschedule_scan_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='scan_end_time',
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='scan_start_time',
        ),
    ]
