# Generated by Django 4.2.10 on 2025-06-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_teachingassignment_assignment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='学分'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='课程ID'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=100, verbose_name='课程名称'),
        ),
    ]
