# Generated by Django 4.2.23 on 2025-06-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_student_user_teacher_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classschedule",
            name="schedule_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="时间安排ID"
            ),
        ),
    ]
