# Generated by Django 5.2.3 on 2025-06-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_classschedule_schedule_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceevent',
            name='event_status',
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='二维码内容'),
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='qr_code_expire_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='二维码过期时间'),
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='status',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='考勤事件状态：1-有效，2-无效'),
        ),
        migrations.AlterField(
            model_name='attendanceevent',
            name='event_date',
            field=models.DateField(verbose_name='考勤日期'),
        ),
        migrations.AlterField(
            model_name='attendanceevent',
            name='scan_end_time',
            field=models.DateTimeField(verbose_name='扫码结束时间'),
        ),
        migrations.AlterField(
            model_name='attendanceevent',
            name='scan_start_time',
            field=models.DateTimeField(verbose_name='扫码开始时间'),
        ),
    ]
